[package]
name = "rustfullstackworkshop"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
uuid = "1.16.0"


[workspace]
members = [
    "api/lib",
    "api/shuttle",
    "shared"
]
resolver = "2"
